In [1]:
from ipywidgets import Textarea

def get_input(change):
    global Input
    Input=change["new"].splitlines()
textarea = Textarea()
textarea.observe(get_input, names='value')
display(textarea)

Textarea(value='')

In [84]:
N, K = map(int, Input[0].split())
a = list(map(int, Input[1].split()))

# しゃくとり法!!
intervalのsumを計算するときにsum()したらここがO(N)かかって全体がO(N^2)になるから気を付ける  
O(n)でできる計算はPyPyよりPythonの方が速い?

## debug

In [99]:
interval = 0
ans = 0
left = 0
right = 0
print(a)
while True:
    print(f'{left=}, {right=}, {interval=}', end=' ')
    if interval < K:
        if right == N:
            print()
            break
        interval += a[right]
        right += 1
    else:
        ans += N - right + 1
        print(f'ans += {N-right+1}', end='')
        interval -= a[left]
        left += 1
    print()
print(ans)

[103, 35322, 232, 342, 21099, 90000, 18843, 9010, 35221, 19352]
left=0, right=0, interval=0 
left=0, right=1, interval=103 
left=0, right=2, interval=35425 
left=0, right=3, interval=35657 
left=0, right=4, interval=35999 
left=0, right=5, interval=57098 ans += 6
left=1, right=5, interval=56995 ans += 6
left=2, right=5, interval=21673 
left=2, right=6, interval=111673 ans += 5
left=3, right=6, interval=111441 ans += 5
left=4, right=6, interval=111099 ans += 5
left=5, right=6, interval=90000 ans += 5
left=6, right=6, interval=0 
left=6, right=7, interval=18843 
left=6, right=8, interval=27853 
left=6, right=9, interval=63074 ans += 2
left=7, right=9, interval=44231 
left=7, right=10, interval=63583 ans += 1
left=8, right=10, interval=54573 ans += 1
left=9, right=10, interval=19352 
36


## submit

In [104]:
def main():
    N, K = map(int, input().split())
    a = list(map(int, input().split()))
    interval = a[0]
    ans = 0
    left = 0
    right = 1
    while True:
        if interval < K:
            if right == N:
                break
            interval += a[right]
            right += 1
        else:
            ans += N - right + 1
            interval -= a[left]
            left += 1
    print(ans)
main()

 10 53462
 103 35322 232 342 21099 90000 18843 9010 35221 19352


36


# Numpy Conv Version
かっこいいけど流石にTLE

## debug

In [32]:
import numpy as np

num = 0
seq = np.array(a)
print(seq)

for i in range(1, N+1):
    kernel = np.ones(i)
    conv = np.convolve(seq, kernel, mode='valid')
    print(conv, conv >= K)
    num += sum(conv >= K)
    
print(num)

[6 1 2 7]
[6. 1. 2. 7.] [False False False False]
[7. 3. 9.] [False False False]
[ 9. 10.] [False  True]
[16.] [ True]
2


In [20]:
signal = np.array(range(10))
kernel = np.ones(2)/2
print(signal, kernel)
np.convolve(signal, kernel, mode='valid')

[0 1 2 3 4 5 6 7 8 9] [0.5 0.5]


array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5])

In [29]:
sum(np.array(range(5)) > 2)

2

## submit

In [35]:
import numpy as np

def main():
    N, K = map(int, input().split())
    a = list(map(int, input().split()))
    num = 0
    seq = np.array(a)
    for i in range(1, N+1):
        num += sum(np.convolve(seq, np.ones(i), mode='valid') >= K)
    print(num)
main()

 10 53462
 103 35322 232 342 21099 90000 18843 9010 35221 19352


36


# 真面目にDP Version
PyPyで出したけどTLE  
知ってた。  
max(N) = 10^5  
O(N(N+1)/2) = O(N^2)

## debug

In [75]:
def count(seq, target):
    return sum([1 if i >= target else 0 for i in seq])

seq = list(a)
ans = count(seq, K)
print(seq)

for i in range(1, N):
    print(f'{i=}, {N-i=}')
    conv = [0]*(N-i)
    for j in range(N-i):
        conv[j] = seq[j] + a[j+i]
    print(conv)
    num = count(conv, K)
    print(f'{num=}')
    ans += num
    seq = conv

print(ans)

[103, 35322, 232, 342, 21099, 90000, 18843, 9010, 35221, 19352]
i=1, N-i=9
[35425, 35554, 574, 21441, 111099, 108843, 27853, 44231, 54573]
num=3
i=2, N-i=8
[35657, 35896, 21673, 111441, 129942, 117853, 63074, 63583]
num=5
i=3, N-i=7
[35999, 56995, 111673, 130284, 138952, 153074, 82426]
num=6
i=4, N-i=6
[57098, 146995, 130516, 139294, 174173, 172426]
num=6
i=5, N-i=5
[147098, 165838, 139526, 174515, 193525]
num=5
i=6, N-i=4
[165941, 174848, 174747, 193867]
num=4
i=7, N-i=3
[174951, 210069, 194099]
num=3
i=8, N-i=2
[210172, 229421]
num=2
i=9, N-i=1
[229524]
num=1
36


## submit

In [76]:
def count(seq, target):
    return sum([1 if i >= target else 0 for i in seq])
def main():
    N, K = map(int, input().split())
    a = list(map(int, input().split()))

    seq = list(a)
    ans = count(seq, K)
    for i in range(1, N):
        conv = [0]*(N-i)
        for j in range(N-i):
            conv[j] = seq[j] + a[j+i]
        ans += count(conv, K)
        seq = conv
    print(ans)
main()

 10 53462
 103 35322 232 342 21099 90000 18843 9010 35221 19352


36
