# まとめ
まず、Pypyなら通ったけど、pythonでは通らなかった。  
1回のループで全部計算するやつの方が、バラバラに4回回すやつよりすこし速かった。  
余計なelseは使わない。初期値と同じ値を代入するelse文が遅くしてた。

In [3]:
from ipywidgets import Textarea

def get_input(change):
    global Input
    Input=change["new"].splitlines()
textarea = Textarea()
textarea.observe(get_input, names='value')
display(textarea)

Textarea(value='')

In [20]:
H, W = map(int, Input[0].split())
S = [list(i) for i in Input[1:]]

# Loop for left, right, up, down respectively
'.' じゃない場合のelseがあるとTLEになる。  
あと、PyPyで出さないとTLEになる。

## debug

In [24]:
left = [[-1]*W for _ in range(H)]
right = [[-1]*W for _ in range(H)]
up = [[-1]*W for _ in range(H)]
down = [[-1]*W for _ in range(H)]

for i in range(H):
    for j in range(W):
        if S[i][j] == '.':
            if j == 0:
                left[i][j] = 0
            else:
                left[i][j] = left[i][j-1] + 1

for i in range(H):
    for j in range(W):
        if S[-1-i][-1-j] == '.':        
            if j == 0:
                right[-1-i][-1-j] = 0
            else:
                right[-1-i][-1-j] = right[-1-i][-1-(j-1)] + 1

for i in range(H):
    for j in range(W):
        if S[i][j] == '.':
            if i == 0:
                up[i][j] = 0
            else:
                up[i][j] = up[i-1][j] + 1

for i in range(H):
    for j in range(W):
        if S[-1-i][-1-j] == '.':
            if i == 0:
                down[-1-i][-1-j] = 0
            else:
                down[-1-i][-1-j] = down[-1-(i-1)][-1-j] + 1
            
ans = 0
temp = [0] * W
for i in range(H):
    for j in range(W):
        temp[j] = left[i][j] + right[i][j] + down[i][j] + up[i][j] + 1
    ans = max(ans, max(temp))
print(ans)

13


## submit

In [23]:
def main():
    H, W = map(int, input().split())
    S = [list(input()) for _ in range(H)]

    left = [[-1]*W for _ in range(H)]
    right = [[-1]*W for _ in range(H)]
    up = [[-1]*W for _ in range(H)]
    down = [[-1]*W for _ in range(H)]

    for i in range(H):
        for j in range(W):
            if S[i][j] == '.':
                if j == 0:
                    left[i][j] = 0
                else:
                    left[i][j] = left[i][j-1] + 1

    for i in range(H):
        for j in range(W):
            if S[-1-i][-1-j] == '.':        
                if j == 0:
                    right[-1-i][-1-j] = 0
                else:
                    right[-1-i][-1-j] = right[-1-i][-1-(j-1)] + 1

    for i in range(H):
        for j in range(W):
            if S[i][j] == '.':
                if i == 0:
                    up[i][j] = 0
                else:
                    up[i][j] = up[i-1][j] + 1

    for i in range(H):
        for j in range(W):
            if S[-1-i][-1-j] == '.':
                if i == 0:
                    down[-1-i][-1-j] = 0
                else:
                    down[-1-i][-1-j] = down[-1-(i-1)][-1-j] + 1
            
    ans = 0
    temp = [0] * W
    for i in range(H):
        for j in range(W):
            temp[j] = left[i][j] + right[i][j] + down[i][j] + up[i][j] + 1
        ans = max(ans, max(temp))
    print(ans)

main()

 4 6
 #..#..
 .....#
 ....#.
 #.#...


NameError: name 'N' is not defined

# Numpy
else消しても速度変わらず。

## debug

In [25]:
import numpy as np

left = np.zeros([H, W], dtype=np.int) - 1
right = np.zeros([H, W], dtype=np.int) - 1
up = np.zeros([H, W], dtype=np.int) - 1
down = np.zeros([H, W], dtype=np.int) - 1 

for i in range(H):
    for j in range(W):
        if S[i][j] == '.':
            if j == 0:
                left[i][j] = 0
            else:
                left[i][j] = left[i][j-1] + 1
            if i == 0:
                up[i][j] = 0
            else:
                up[i][j] = up[i-1][j] + 1
            
        if S[-1-i][-1-j] == '.':
            if j == 0:
                right[-1-i][-1-j] = 0
            else:
                right[-1-i][-1-j] = right[-1-i][-1-(j-1)] + 1
            if i == 0:
                down[-1-i][-1-j] = 0
            else:
                down[-1-i][-1-j] = down[-1-(i-1)][-1-j] + 1

print(np.max(left+right+up+down) + 1)

13


In [61]:
for s in S:
    print(s)
print('left\n', left)
print('right\n', right)
print('up\n', up)
print('down\n', down)
print('horizontal\n', left+right)
print('vertical\n', up+down)
print('all\n', left+right+up+down)

['#', '.', '.', '#', '.', '.']
['.', '.', '.', '.', '.', '#']
['.', '.', '.', '.', '#', '.']
['#', '.', '#', '.', '.', '.']
left
 [[-1  0  1 -1  0  1]
 [ 0  1  2  3  4 -1]
 [ 0  1  2  3 -1  0]
 [-1  0 -1  0  1  2]]
right
 [[-1  1  0 -1  1  0]
 [ 4  3  2  1  0 -1]
 [ 3  2  1  0 -1  0]
 [-1  0 -1  2  1  0]]
up
 [[-1  0  0 -1  0  0]
 [ 0  1  1  0  1 -1]
 [ 1  2  2  1 -1  0]
 [-1  3 -1  2  0  1]]
down
 [[-1  3  2 -1  1  0]
 [ 1  2  1  2  0 -1]
 [ 0  1  0  1 -1  1]
 [-1  0 -1  0  0  0]]
horizontal
 [[-2  1  1 -2  1  1]
 [ 4  4  4  4  4 -2]
 [ 3  3  3  3 -2  0]
 [-2  0 -2  2  2  2]]
vertical
 [[-2  3  2 -2  1  0]
 [ 1  3  2  2  1 -2]
 [ 1  3  2  2 -2  1]
 [-2  3 -2  2  0  1]]
all
 [[-4  4  3 -4  2  1]
 [ 5  7  6  6  5 -4]
 [ 4  6  5  5 -4  1]
 [-4  3 -4  4  2  3]]


## submit
<span style="color: red; "><u>TLE</u></span>

In [47]:
import numpy as np

def main():
    H, W = map(int, input().split())
    S = [list(input()) for _ in range(H)]
    
    left = np.zeros([H, W], dtype=np.int) - 1
    right = np.zeros([H, W], dtype=np.int) - 1
    up = np.zeros([H, W], dtype=np.int) - 1
    down = np.zeros([H, W], dtype=np.int) - 1

    for i in range(H):
        for j in range(W):
            if S[i][j] == '.':
                if j == 0:
                    left[i][j] = 0
                else:
                    left[i][j] = left[i][j-1] + 1
                if i == 0:
                    up[i][j] = 0
                else:
                    up[i][j] = up[i-1][j] + 1
            
            if S[-1-i][-1-j] == '.':
                if j == 0:
                    right[-1-i][-1-j] = 0
                else:
                    right[-1-i][-1-j] = right[-1-i][-1-(j-1)] + 1
                if i == 0:
                    down[-1-i][-1-j] = 0
                else:
                    down[-1-i][-1-j] = down[-1-(i-1)][-1-j] + 1
                
    print(np.max(left+right+up+down) + 1)

main()

 8 8
 ..#...#.
 ....#...
 ##......
 ..###..#
 ...#..#.
 ##....#.
 #...#...
 ###.#..#


13


### memo

# Pypy

## debug

In [27]:
left = [[-1]*W for _ in range(H)]
right = [[-1]*W for _ in range(H)]
up = [[-1]*W for _ in range(H)]
down = [[-1]*W for _ in range(H)]

for i in range(H):
    for j in range(W):
        if S[i][j] == '.':
            if j == 0:
                left[i][j] = 0
            else:
                left[i][j] = left[i][j-1] + 1
            if i == 0:
                up[i][j] = 0
            else:
                up[i][j] = up[i-1][j] + 1
            
        if S[-1-i][-1-j] == '.':
            if j == 0:
                right[-1-i][-1-j] = 0
            else:
                right[-1-i][-1-j] = right[-1-i][-1-(j-1)] + 1
            if i == 0:
                down[-1-i][-1-j] = 0
            else:
                down[-1-i][-1-j] = down[-1-(i-1)][-1-j] + 1

ans = 0
temp = [0] * W
for i in range(H):
    for j in range(W):
        temp[j] = left[i][j] + right[i][j] + down[i][j] + up[i][j] + 1
    ans = max(ans, max(temp))
print(ans)

13


## submit

In [ ]:
def main():
    H, W = map(int, input().split())
    S = [list(input()) for _ in range(H)]
    
    left = [[-1]*W for _ in range(H)]
    right = [[-1]*W for _ in range(H)]
    up = [[-1]*W for _ in range(H)]
    down = [[-1]*W for _ in range(H)]

    for i in range(H):
        for j in range(W):
            if S[i][j] == '.':
                if j == 0:
                    left[i][j] = 0
                else:
                    left[i][j] = left[i][j-1] + 1
                if i == 0:
                    up[i][j] = 0
                else:
                    up[i][j] = up[i-1][j] + 1

            if S[-1-i][-1-j] == '.':
                if j == 0:
                    right[-1-i][-1-j] = 0
                else:
                    right[-1-i][-1-j] = right[-1-i][-1-(j-1)] + 1
                if i == 0:
                    down[-1-i][-1-j] = 0
                else:
                    down[-1-i][-1-j] = down[-1-(i-1)][-1-j] + 1

    ans = 0
    temp = [0] * W
    for i in range(H):
        for j in range(W):
            temp[j] = left[i][j] + right[i][j] + down[i][j] + up[i][j] + 1
        ans = max(ans, max(temp))
    print(ans)

main()