In [1]:
from ipywidgets import Textarea

def get_input(change):
    global Input
    Input=change["new"].splitlines()
textarea = Textarea()
textarea.observe(get_input, names='value')
display(textarea)

Textarea(value='')

# 横と縦を両方bit全探索

## debug

In [42]:
from itertools import product
import numpy as np

H, W, K = map(int, Input[0].split())
C = [list(i) for i in Input[1:]]

C = np.array(C)
C = np.where(C == '.', 0, C)
C = np.where(C == '#', 1, C)
C = C.astype(np.int)
print(C)

ans = 0

for h_bits in product(*[range(2) for _ in range(H)]):
    print('############')
    print(f'{h_bits=}')
    ch = C.copy()
    print(ch)
    for i,h in enumerate(h_bits):
        if h == 1:
            ch[i] = 0
    print(ch)
    print()
    for w_bits in product(*[range(2) for _ in range(W)]):
        print(f'{w_bits=}')
        cw = ch.copy()
        for j,w in enumerate(w_bits):
            if w == 1:
                cw[:,j] = 0
        if cw.sum() == K:
            ans += 1
        print(cw)
        print('\n')

print(ans)

[[1 1]
 [1 1]]
############
h_bits=(0, 0)
[[1 1]
 [1 1]]
[[1 1]
 [1 1]]

w_bits=(0, 0)
[[1 1]
 [1 1]]


w_bits=(0, 1)
[[1 0]
 [1 0]]


w_bits=(1, 0)
[[0 1]
 [0 1]]


w_bits=(1, 1)
[[0 0]
 [0 0]]


############
h_bits=(0, 1)
[[1 1]
 [1 1]]
[[1 1]
 [0 0]]

w_bits=(0, 0)
[[1 1]
 [0 0]]


w_bits=(0, 1)
[[1 0]
 [0 0]]


w_bits=(1, 0)
[[0 1]
 [0 0]]


w_bits=(1, 1)
[[0 0]
 [0 0]]


############
h_bits=(1, 0)
[[1 1]
 [1 1]]
[[0 0]
 [1 1]]

w_bits=(0, 0)
[[0 0]
 [1 1]]


w_bits=(0, 1)
[[0 0]
 [1 0]]


w_bits=(1, 0)
[[0 0]
 [0 1]]


w_bits=(1, 1)
[[0 0]
 [0 0]]


############
h_bits=(1, 1)
[[1 1]
 [1 1]]
[[0 0]
 [0 0]]

w_bits=(0, 0)
[[0 0]
 [0 0]]


w_bits=(0, 1)
[[0 0]
 [0 0]]


w_bits=(1, 0)
[[0 0]
 [0 0]]


w_bits=(1, 1)
[[0 0]
 [0 0]]


0


## submit

In [36]:
from itertools import product
import numpy as np

H, W, K = map(int, input().split())
C = [list(input()) for _ in range(H)]

C = np.array(C)
C = np.where(C == '.', 0, C)
C = np.where(C == '#', 1, C)
C = C.astype(np.int)

ans = 0

for h_bits in product(*[range(2) for _ in range(H)]):
    ch = C.copy()
    for i,h in enumerate(h_bits):
        if h == 1:
            ch[i] = 0
    for w_bits in product(*[range(2) for _ in range(W)]):
        cw = ch.copy()
        for j,w in enumerate(w_bits):
            if w == 1:
                cw[:,j] = 0
        if cw.sum() == K:
            ans += 1

print(ans)

 2 3 2
 ..#
 ###


5
